config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'dashboard#index'
  resources :referees
  resources :reports
end

app/models/referee.rb
# Responsible for maintaining the ActiveRecord referee model
class Referee < ActiveRecord::Base
  has_many :reports
  belongs_to :region

  validates :first_name, :last_name, :region_id, :email, presence: true
  validates :epee_rating,
            :foil_rating,
            :sabre_rating,
            numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }

  delegate :name, to: :region, prefix: true

  def display_name
    "#{first_name} #{last_name}"
  end

  def search_name
    "#{last_name} #{first_name}"
  end
end

app/models/region.rb
# Responsible for the ActiveRecord region model
class Region < ActiveRecord::Base
  has_many :referees
  has_many :users
end

app/models/report.rb
# Responsible for maintaining ActiveRecord Report model
class Report < ActiveRecord::Base
  belongs_to :author, class_name: 'User'
  belongs_to :referee

  delegate :display_name, to: :author, prefix: true
  delegate :display_name, to: :referee, prefix: true

  validates :rules_knowledge_score, :right_of_way_score, :strip_control_score,
            numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
end

app/models/user.rb
# responsible for maintaining the ActiveRecord User model
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :first_name, :last_name, :region_id, presence: true

  belongs_to :region
  has_many :referees
  delegate :name, to: :region, prefix: true

  def display_name
    "#{first_name} #{last_name}"
  end

  def search_name
    "#{last_name} #{first_name}"
  end
end

app/controllers/application_controller.rb
# Responsible for routing requests
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name << :last_name << :region_id
    devise_parameter_sanitizer.for(:sign_in) << :first_name << :last_name << :region_id
    devise_parameter_sanitizer.for(:account_update) << :first_name << :last_name << :region_id
  end
end

app/controllers/dashboard_controller.rb
# responsible for routing dashboard requests
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/referees_controller.rb
# Responsible for routing /referees/ requests
class RefereesController < ApplicationController
  def index
    render locals: { referees: Referee.all.order('last_name asc') }
  end

  def new
    render 'edit',
           locals: { referee: Referee.new, action_title: 'New', submit_path: referees_path }
  end

  def create
    referee = Referee.new(params[:referee].permit(permitted_params))
    if referee.save
      redirect_to referee
    else
      render 'edit'
    end
  end

  def show
    render locals: { referee: Referee.find(params[:id]) }
  end

  def edit
    ref = Referee.find(params[:id])
    render locals: { referee: ref, action_title: 'Edit', submit_path: referee_path(ref) }
  end

  def update
    referee = Referee.find(params[:id])
    if referee.update(params[:referee].permit(permitted_params))
      redirect_to referee
    else
      render 'edit', locals: { referee: referee,
                               action_title: 'Edit',
                               submit_path: referee_path(referee) }
    end
  end

  private

  def permitted_params
    [
      :email,
      :first_name,
      :last_name,
      :region_id,
      :epee_rating,
      :foil_rating,
      :sabre_rating
    ]
  end
end

app/controllers/reports_controller.rb
# Responsible for routing reports HTTP requests
class ReportsController < ApplicationController
  def index
    render locals: { reports: Report.where(author: current_user) }
  end

  def show
    render locals: { report: Report.find(params[:id]) }
  end

  def new
    render 'edit',
           locals: { report: Report.new, action_name: 'New', submit_path: reports_path }
  end

  def create
    report = Report.new(params[:report].permit(permitted_params))
    report.author = current_user

    if report.save
      redirect_to report
    else
      render 'edit', locals: { report: report, action_name: 'New', submit_path: reports_path }
    end
  end

  private

  def permitted_params
    [
      :referee_id,
      :rules_knowledge_score,
      :rules_knowledge_comments,
      :right_of_way_score,
      :right_of_way_comments,
      :strip_control_score,
      :strip_control_comments
    ]
  end
end

app/helpers/application_helper.rb
# responsible for common methods throughout the app
module ApplicationHelper
end

app/views/dashboard/index.html.haml
%h2 Welcome to the Scoresheet!

%p Future home of the Regional Referee Observer website

- if current_user
  %p Welcome, #{current_user.first_name} #{current_user.last_name}. Your email is #{current_user.email} and your region is #{current_user.region.name}
  %a= link_to 'Log Out', destroy_user_session_path, method: :delete

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{ data: { toggle: 'collapse', target: '#navbar-collapse-1' },
        'aria-expanded' => false }
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{ href: root_path }Scoresheet
    .navbar-collapse.collapse#navbar-collapse-1
      %ul.nav.navbar-nav
        %li
          %a{ href: root_path }
            %span.glyphicon.glyphicon-home
            %span.sr-only Home
        %li
          %a{ href: referees_path } Referees
        %li
          %a{ href: reports_path } Reports
      %ul.nav.navbar-nav.navbar-right
        %li
          %a{ href: edit_user_registration_path }
            %span.glyphicon.glyphicon-user
            %span.sr-only My Profile
        %li
          %a{ href: destroy_user_session_path } Log Out

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ :content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }/
    %title Scoresheet
    = stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'
    = stylesheet_link_tag 'bootstrap.min.css'
    = stylesheet_link_tag 'application', media: 'all'
    -# stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body.container
    = render 'layouts/navbar'
    - if notice.present?
      %p.alert.alert-info= notice
    - if alert.present?
      %p.alert.alert-danger= alert
    = yield

app/views/referees/edit.html.haml
%h1 #{action_name.titleize} Referee

= form_for(referee, url: submit_path) do |f|
  - if referee.errors.any?
    .errors.bg-danger
      %h3 #{pluralize(referee.errors.count, 'error')} prohibited this from being saved:
      %ul
        - referee.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :first_name
    = f.text_field :first_name, autofocus: true, class: 'form-control'
  .form-group
    = f.label :last_name
    = f.text_field :last_name, class: 'form-control'
  .form-group
    = f.label :email
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :region
    = f.select(:region_id, Region.all.map { |r| [r.name, r.id] },
      class: 'form-control', include_blank: true)
  .form-group
    = f.label :epee_rating
    = f.number_field :epee_rating, class: 'form-control'
  .form_group
    = f.label :foil_rating
    = f.number_field :foil_rating, class: 'form-control'
  .form-group
    = f.label :sabre_rating
    = f.number_field :sabre_rating, class: 'form-control'
  .actions
    = f.submit 'Submit', class: 'btn btn-primary'

app/views/referees/index.html.haml
%h1 Referees

%a.btn.btn-default{ href: new_referee_path } New Referee
%table.table.table-hover
  %tr
    %th Referee Name
    %th New Report
    %th Section
    %th Foil Rating
    %th Epee Rating
    %th Sabre Rating
    %th Edit
  - referees.each do |referee|
    %tr
      %td= link_to(referee.display_name, referee_path(referee))
      %td= link_to(tag('span', class: 'glyphicon glyphicon-plus'))
      %td= referee.region_name
      %td= referee.epee_rating
      %td= referee.foil_rating
      %td= referee.sabre_rating
      %td= link_to(tag('span', class: 'glyphicon glyphicon-cog'), edit_referee_path(referee))

app/views/referees/show.html.haml
%h1= referee.display_name

%table.table
  %tr
    %th Region
    %td= referee.region_name
  %tr
    %th Email
    %td= referee.email
  %tr
    %th Foil Rating
    %td= referee.foil_rating
  %tr
    %th Epee Rating
    %td= referee.epee_rating
  %tr
    %th Sabre Rating
    %td= referee.sabre_rating

app/views/reports/edit.html.haml
%h1 #{action_name.titleize} Report

= form_for(report, url: submit_path) do |f|
  - if report.errors.any?
    .errors.bg-danger
      %h3 #{pluralize(report.errors.count, 'error')} prohibited this from being saved:
      %ul
        - report.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :referee
    = f.select(:referee_id, Referee.all.order(:last_name).map { |r| [r.display_name, r.id] },
      class: 'form-control', include_blank: true)
  .form-group
    = f.label :rules_knowledge_score
    = f.number_field :rules_knowledge_score, class: 'form-control'
  .form-group
    = f.label :rules_knowledge_comments
    = f.text_area :rules_knowledge_comments, class: 'form-control'
  .form-group
    = f.label :right_of_way_score
    = f.number_field :right_of_way_score, class: 'form-control'
  .form-group
    = f.label :right_of_way_comments
    = f.text_area :right_of_way_comments, class: 'form-control'
  .form-group
    = f.label :strip_control_score
    = f.number_field :strip_control_score, class: 'form-control'
  .form-group
    = f.label :strip_control_comments
    = f.text_area :strip_control_comments, class: 'form-control'
  .actions
    = f.submit 'Submit', class: 'btn btn-primary'

app/views/reports/index.html.haml
%h1 Your Reports

%a.btn.btn-default{ href: new_report_path } New Report
%table.table
  %tr
    %th Referee Name
  - reports.each do |report|
    %tr
      %td= link_to(report.referee_display_name, report_path(report.referee))

app/views/reports/show.html.haml
%h1 Observation Report for #{report.referee_display_name}
%h3 Written by #{report.author_display_name}

%table.table
  %tr
    %th Rules Knowledge Score
    %td= report.rules_knowledge_score
  %tr
    %th Rules Knowledge Comments
    %td= report.rules_knowledge_comments
  %tr
    %th Right of Way Knowledge Score
    %td= report.right_of_way_score
  %tr
    %th Right of Way Comments
    %td= report.right_of_way_comments
  %tr
    %th Strip Control Score
    %td= report.strip_control_score
  %tr
    %th Strip Control Comments
    %td= report.strip_control_comments